/*
 * terminal_usart_settings.h
 *
 * Created: 26.9.2011 22:04:25
 *  Author: savpek
 */ 
#ifndef TERMINAL_USART_SETTINGS_H_
#define TERMINAL_USART_SETTINGS_H_

/* Startup settings for terminal, includes USART settings etc... */
#define TERMINAL_USART 		(&AVR32_USART0)
#define TERMINAL_BAUDRATE	56000
#define TERMINAL_CHARLENGTH	8
#define TERMINAL_PARITYPE	USART_NO_PARITY
#define TERMINAL_STOPBITS	USART_2_STOPBITS
#define TERMINAL_CHANNELMODE USART_NORMAL_CHMODE

#define TERMINAL_USART_RX_PIN        AVR32_USART0_RXD_0_PIN
#define TERMINAL_USART_RX_FUNCTION   AVR32_USART0_RXD_0_FUNCTION
#define TERMINAL_USART_TX_PIN        AVR32_USART0_TXD_0_PIN
#define TERMINAL_USART_TX_FUNCTION   AVR32_USART0_TXD_0_FUNCTION

#endif /* TERMINAL_USART_SETTINGS_H_ */