/*
 * hw_settings.h
 *
 *   \created: 21.2.2012 23:53:13
 *  \author: savpek
 */ 


#ifndef HW_SETTINGS_H_
#define HW_SETTINGS_H_

#define PIN_CONF_LCD_E_PIN
#define PIN_CONF_LCD_E_FUNCTION
#define PIN_CONF_LCD_RW_PIN
#define PIN_CONF_LCD_RW_FUNCTION
#define PIN_CONF_LCD_RS_PIN
#define PIN_CONF_LCD_RS_FUNCTION
#define PIN_CONF_LCD_DB7_PIN
#define PIN_CONF_LCD_DB7_FUNCTION
#define PIN_CONF_LCD_DB6_PIN
#define PIN_CONF_LCD_DB6_FUNCTION
#define PIN_CONF_LCD_DB5_PIN
#define PIN_CONF_LCD_DB5_FUNCTION
#define PIN_CONF_LCD_DB4_PIN
#define PIN_CONF_LCD_DB4_FUNCTION
#define PIN_CONF_LCD_DB3_PIN
#define PIN_CONF_LCD_DB3_FUNCTION
#define PIN_CONF_LCD_DB2_PIN
#define PIN_CONF_LCD_DB2_FUNCTION
#define PIN_CONF_LCD_DB1_PIN
#define PIN_CONF_LCD_DB1_FUNCTION
#define PIN_CONF_LCD_DB0_PIN
#define PIN_CONF_LCD_DB0_FUNCTION


#define PIN_CONF_MOSI_PIN
#define PIN_CONF_MOSI_FUNCTION
#define PIN_CONF_MISO_PIN
#define PIN_CONF_MISO_FUNCTION


#endif /* HW_SETTINGS_H_ */