/*! @brief Settings for TLCR REVISION 1 HW GPIO
 *
 *	@file	gpio_config.h
 *	@author savpek							*/

#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_

/*! @def FUNCTION MAP FOR	PIN 0: */
#define INITD_GPIO_PIN_0_F			AVR32_USART0_TXD_0_FUNCTION

/*! @def FUNCTION MAP FOR	PIN 1: */
#define INITD_GPIO_PIN_1_F			AVR32_USART0_RXD_0_FUNCTION

/*! @def FUNCTION MAP FOR	PIN 2: */
#define INITD_GPIO_PIN_2_F			AVR32_USART0_RTS_0_FUNCTION

/*! @def FUNCTION MAP FOR	PIN 3: */
#define INITD_GPIO_PIN_3_F			AVR32_USART0_CTS_0_0_FUNCTION

/*! @def FUNCTION MAP FOR	PIN 4: */
#define INITD_GPIO_PIN_4_F			AVR32_USART0_RXD_0_FUNCTION


#define USART_RX_PIN        AVR32_USART0_RXD_0_PIN
#define USART_RX_FUNCTION   AVR32_USART0_RXD_0_FUNCTION
#define USART_TX_PIN        AVR32_USART0_TXD_0_PIN
#define USART_TX_FUNCTION   AVR32_USART0_TXD_0_FUNCTION
#define USART_CTS_PIN       AVR32_USART0_CTS_0_0_PIN
#define USART_CTS_FUNCTION  AVR32_USART0_CTS_0_0_FUNCTION
#define USART_RTS_PIN       AVR32_USART0_RTS_0_PIN
#define USART_RTS_FUNCTION  AVR32_USART0_RTS_0_FUNCTION

/*! @def ALIASES FOR		PIN 0: */
#define INITD_GPIO_TXD_0_PIN		0

#endif /* GPIO_CONFIG_H_ */