/*! @brief Settings for TLCR REVISION 1 HW GPIO
 *
 *	@file	gpio_config.h
 *	@author savpek							*/

#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_

/*! UNDEFINE PINS NOT USED BY APPLICATION!
 *	They are not initialized if not defined here! */

#define INITD_GPIO_OUTPUT			GPIO_DIR_OUTPUT
#define INITD_GPIO_INPUT			GPIO_DIR_INPUT
#define INITD_GPIO_INPUT_W_PULLUP	GPIO_DIR_INPUT|GPIO_PULL_UP

/*! @def FUNCTION, CONFIG and ALIAS for PA00 */
#define INITD_GPIO_PA00_FUNCTION	AVR32_USART0_TXD_0_FUNCTION
#define INITD_GPIO_PA00_CONFIG		INITD_GPIO_OUTPUT
#define GPIO_USART0_TXD_PIN			AVR32_PIN_PA00

/*! @def FUNCTION and ALIAS for PA01 */
#define INITD_GPIO_PA01_FUNCTION	AVR32_USART0_RXD_0_FUNCTION
#define GPIO_USART0_RXD_PIN			AVR32_PIN_PA01

/*! @def FUNCTION and ALIAS for PA02 */
#define INITD_GPIO_PA02_FUNCTION	AVR32_USART0_RTS_0_FUNCTION
#define GPIO_USART0_RTS_PIN			AVR32_PIN_PA02

/*! @def FUNCTION and ALIAS for PA03 */
#define INITD_GPIO_PA03_FUNCTION	AVR32_USART0_CTS_0_0_FUNCTION
#define GPIO_USART0_CTS_PIN			AVR32_PIN_PA03

/*! @def FUNCTION, CONFIG and ALIAS for PA00 */
#define INITD_GPIO_PA08_FUNCTION	0
#define INITD_GPIO_PA08_CONFIG		INITD_GPIO_OUTPUT
#define GPIO_LCD_LED_PIN			AVR32_PIN_PA08


/*! @def FUNCTION and ALIAS for PA04 */
//#define INITD_GPIO_P04_F
//#define GPIO_TEMPLATE_PIN_ALIAS

/*! @def FUNCTION and ALIAS for PA05 */
//#define INITD_GPIO_P05_F
//#define GPIO_TEMPLATE_PIN_ALIAS

/*! @def FUNCTION and ALIAS for PA06 */
//#define INITD_GPIO_P06_F
//#define GPIO_TEMPLATE_PIN_ALIAS

/*! @def FUNCTION and ALIAS for PA07 */
//#define INITD_GPIO_P07_F
//#define GPIO_TEMPLATE_PIN_ALIAS

/*! @def FUNCTION and ALIAS for PA08 */
#define INITD_GPIO_P08_F			0
#define GPIO_LCD_LED_PIN			AVR32_PIN_PA08

/*! @def FUNCTION and ALIAS for PA09 */
//#define INITD_GPIO_P09_F
//#define GPIO_TEMPLATE_PIN_ALIAS
#endif /* GPIO_CONFIG_H_ */