/*! @brief Settings for TLCR REVISION 1 HW GPIO
 *
 *	@file	gpio_config.h
 *	@author savpek							*/

#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_

/*! UNDEFINE PINS NOT USED BY APPLICATION!
 *	They are not initialized if not defined here! */

/*! You if you use pin as GPIO module:
 *	define: INITD_GPIO_PXXX_CONFIG
 *
 *	If you use some other module (like PWMA):
 *	define: INITID_GPIO_PXXX_FUNCTION */

#define INITD_GPIO_OUTPUT			GPIO_DIR_OUTPUT
#define INITD_GPIO_INPUT			GPIO_DIR_INPUT
#define INITD_GPIO_INPUT_W_PULLUP	GPIO_DIR_INPUT|GPIO_PULL_UP

/*! @def FUNCTION, CONFIG and ALIAS for PA00 */
#define INITD_GPIO_PA00_FUNCTION	AVR32_USART0_TXD_0_FUNCTION
//#define INITD_GPIO_PA00_CONFIG
#define IOPIN_USART0_TXD			AVR32_PIN_PA00

/*! @def FUNCTION and ALIAS for PA01 */
#define INITD_GPIO_PA01_FUNCTION	AVR32_USART0_RXD_0_FUNCTION
//#define INITD_GPIO_PA01_CONFIG
#define IOPIN_USART0_RXD			AVR32_PIN_PA01

/*! @def FUNCTION and ALIAS for PA02 */
#define INITD_GPIO_PA02_FUNCTION	AVR32_USART0_RTS_0_FUNCTION
//#define INITD_GPIO_PA02_CONFIG
#define IOPIN_USART0_RTS			AVR32_PIN_PA02

/*! @def FUNCTION and ALIAS for PA03 */
//#define INITD_GPIO_PA03_FUNCTION	AVR32_USART0_CTS_0_0_FUNCTION
//#define INITD_GPIO_PA03_CONFIG
//#define IOPIN_					AVR32_PIN_PA03

/*! @def FUNCTION and ALIAS for PA04 */
//#define INITD_GPIO_PA04_FUNCTION	0
//#define INITD_GPIO_PA04_CONFIG
//#define IOPIN_					AVR32_PIN_PA04

/*! @def FUNCTION and ALIAS for PA05 */
//#define INITD_GPIO_PA05_FUNCTION	0
//#define INITD_GPIO_PA05_CONFIG
//#define IOPIN_					AVR32_PIN_PA05

/*! @def FUNCTION and ALIAS for PA06 */
//#define INITD_GPIO_PA06_FUNCTION	0
//#define INITD_GPIO_PA06_CONFIG
//#define IOPIN_					AVR32_PIN_PA06

/*! @def FUNCTION and ALIAS for PA07 */
//#define INITD_GPIO_PA07_FUNCTION	0
//#define INITD_GPIO_PA07_CONFIG
//#define IOPIN_			AVR32_PIN_PA07

/*! @def FUNCTION, CONFIG and ALIAS for PA08 */
#define INITD_GPIO_PA08_FUNCTION	0
#define INITD_GPIO_PA08_CONFIG		INITD_GPIO_OUTPUT
#define IOPIN_LCD_LED				AVR32_PIN_PA08

/*! @def FUNCTION and ALIAS for PA09 */
//#define INITD_GPIO_PA09_FUNCTION	0
//#define INITD_GPIO_PA09_CONFIG
//#define IOPIN_			AVR32_PIN_PA09

/*! @def FUNCTION and ALIAS for PA10 */
//#define INITD_GPIO_PA10_FUNCTION	0
//#define INITD_GPIO_PA10_CONFIG
//#define IOPIN_			AVR32_PIN_PA10

/*! @def FUNCTION and ALIAS for PA11 */
//#define INITD_GPIO_PA11_FUNCTION	0
//#define INITD_GPIO_PA11_CONFIG
//#define IOPIN_			AVR32_PIN_PA11

/*! @def FUNCTION and ALIAS for PA12 */
//#define INITD_GPIO_PA12_FUNCTION	0
//#define INITD_GPIO_PA12_CONFIG
//#define IOPIN_			AVR32_PIN_PA12

/*! @def FUNCTION and ALIAS for PA13 */
//#define INITD_GPIO_PA13_FUNCTION	0
//#define INITD_GPIO_PA13_CONFIG
//#define IOPIN_			AVR32_PIN_PA13

/*! @def FUNCTION and ALIAS for PA14 */
//#define INITD_GPIO_PA14_FUNCTION	0
//#define INITD_GPIO_PA14_CONFIG
//#define IOPIN_			AVR32_PIN_PA14

/*! @def FUNCTION and ALIAS for PA15 */
//#define INITD_GPIO_PA15_FUNCTION	0
//#define INITD_GPIO_PA15_CONFIG
//#define IOPIN_			AVR32_PIN_PA15

/*! @def FUNCTION and ALIAS for PA16 */
//#define INITD_GPIO_PA16_FUNCTION	0
//#define INITD_GPIO_PA16_CONFIG
//#define IOPIN_			AVR32_PIN_PA16

/*! @def FUNCTION and ALIAS for PA17 */
#define INITD_GPIO_PA17_FUNCTION	0
#define INITD_GPIO_PA17_CONFIG		INITD_GPIO_OUTPUT	
#define IOPIN_LCD_RS				AVR32_PIN_PA17

/*! @def FUNCTION and ALIAS for PA18 */
#define INITD_GPIO_PA18_FUNCTION	0
#define INITD_GPIO_PA18_CONFIG		INITD_GPIO_OUTPUT
#define IOPIN_LCD_E					AVR32_PIN_PA18

/*! @def FUNCTION and ALIAS for PA19 */
//#define INITD_GPIO_PA19_FUNCTION	0
//#define INITD_GPIO_PA19_CONFIG
//#define IOPIN_			AVR32_PIN_PA19

/*! @def FUNCTION and ALIAS for PA20 */
#define INITD_GPIO_PA20_FUNCTION	0
#define INITD_GPIO_PA20_CONFIG		INITD_GPIO_OUTPUT
#define IOPIN_LCD_DB4				AVR32_PIN_PA20

/*! @def FUNCTION and ALIAS for PA21 */
#define INITD_GPIO_PA21_FUNCTION	0
#define INITD_GPIO_PA21_CONFIG		INITD_GPIO_OUTPUT
#define IOPIN_LCD_DB5				AVR32_PIN_PA21

/*! @def FUNCTION and ALIAS for PA22 */
#define INITD_GPIO_PA22_FUNCTION	0
#define INITD_GPIO_PA22_CONFIG		INITD_GPIO_OUTPUT
#define IOPIN_LCD_DB6				AVR32_PIN_PA22

/*! @def FUNCTION and ALIAS for PB00 */
#define INITD_GPIO_PB00_FUNCTION	0
#define INITD_GPIO_PB00_CONFIG		INITD_GPIO_OUTPUT
#define IOPIN_LCD_DB7				AVR32_PIN_PB00

/*! @def FUNCTION and ALIAS for PB01 */
//#define INITD_GPIO_PB01_FUNCTION	0
//#define INITD_GPIO_PB01_CONFIG	
//#define IOPIN_				AVR32_PIN_PB01

/*! @def FUNCTION and ALIAS for PB02 */
//#define INITD_GPIO_PB02_FUNCTION	0
//#define INITD_GPIO_PB02_CONFIG	
//#define IOPIN_				AVR32_PIN_PB02

/*! @def FUNCTION and ALIAS for PB03 */
//#define INITD_GPIO_PB03_FUNCTION	0
//#define INITD_GPIO_PB03_CONFIG	
//#define IOPIN_				AVR32_PIN_PB03

/*! @def FUNCTION and ALIAS for PB04 */
//#define INITD_GPIO_PB04_FUNCTION	0
//#define INITD_GPIO_PB04_CONFIG	
//#define IOPIN_				AVR32_PIN_PB04

/*! @def FUNCTION and ALIAS for PB05 */
//#define INITD_GPIO_PB05_FUNCTION	0
//#define INITD_GPIO_PB05_CONFIG	
//#define IOPIN_				AVR32_PIN_PB05

/*! @def FUNCTION and ALIAS for PB06 */
//#define INITD_GPIO_PB06_FUNCTION	0
//#define INITD_GPIO_PB06_CONFIG	
//#define IOPIN_				AVR32_PIN_PB06

/*! @def FUNCTION and ALIAS for PB07 */
//#define INITD_GPIO_PB07_FUNCTION	0
//#define INITD_GPIO_PB07_CONFIG	
//#define IOPIN_				AVR32_PIN_PB07

/*! @def FUNCTION and ALIAS for PB08 */
//#define INITD_GPIO_PB08_FUNCTION	0
//#define INITD_GPIO_PB08_CONFIG	
//#define IOPIN_				AVR32_PIN_PB08

/*! @def FUNCTION and ALIAS for PB09 */
//#define INITD_GPIO_PB09_FUNCTION	0
//#define INITD_GPIO_PB09_CONFIG	
//#define IOPIN_				AVR32_PIN_PB09

/*! @def FUNCTION and ALIAS for PB10 */
//#define INITD_GPIO_PB10_FUNCTION	0
//#define INITD_GPIO_PB10_CONFIG	
//#define IOPIN_				AVR32_PIN_PB10

/*! @def FUNCTION and ALIAS for PB11 */
//#define INITD_GPIO_PB11_FUNCTION	0
//#define INITD_GPIO_PB11_CONFIG	
//#define IOPIN_				AVR32_PIN_PB11

/*! @def FUNCTION and ALIAS for PB12 */
//#define INITD_GPIO_PB12_FUNCTION	0
//#define INITD_GPIO_PB12_CONFIG	
//#define IOPIN_				AVR32_PIN_PB12
#endif /* GPIO_CONFIG_H_ */